# Generated by Django 3.0.5 on 2020-04-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0002_auto_20200429_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
    ]
